version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "5000:80"
    networks:
      - app-network
    environment:
      - PORT=80
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    environment:
      - REACT_APP_API=http://localhost:5000
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge